Repository robinostlund/homeassistant-volkswagencarnet, pull requests merged in 2021-05, with the labels that each got.

#281 Add/Rename sensors as in library
  custom_components/volkswagencarnet/const.py
Labels: bug, enhancement

#282 Update dependency to 4.4.3.0
  custom_components/volkswagencarnet/manifest.json
  requirements.txt
Labels: enhancement

#285 Update on login issue - help wanted
  README.md
Labels: enhancement

#286 GAH! Typo!
  README.md
Labels: enhancement

#289 Uses configured region when setting up the connection.
  custom_components/volkswagencarnet/__init__.py
  custom_components/volkswagencarnet/config_flow.py
  custom_components/volkswagencarnet/const.py
  custom_components/volkswagencarnet/strings.json
  custom_components/volkswagencarnet/translations/en.json
Labels: enhancement

#288 Update README.md
  README.md
Labels: enhancement

#290 Bumps api to 4.4.31
  custom_components/volkswagencarnet/manifest.json
  requirements.txt
Labels: enhancement

#292 Update on working countries/Regions
  README.md
Labels: enhancement

#293 Update on "Mutable"
  custom_components/volkswagencarnet/strings.json
Labels: enhancement

#291 Clarification on "mutable".
  custom_components/volkswagencarnet/translations/en.json
Labels: enhancement

#296 Removed old information.
  README.md
Labels: enhancement

#297 Fix crash due to missing key in options after upgrade
  custom_components/volkswagencarnet/__init__.py
  custom_components/volkswagencarnet/config_flow.py
Labels: bug

#298 Update README.md
  README.md
Labels: enhancement

#301 Bumps api module to 4.4.32
  custom_components/volkswagencarnet/manifest.json
  requirements.txt
Labels: bug, enhancement

#302 fix electric range for hybrid cars and charging time
  custom_components/volkswagencarnet/manifest.json
  requirements.txt
Labels: bug

#300 Fixes conversion to miles
  custom_components/volkswagencarnet/__init__.py
  custom_components/volkswagencarnet/config_flow.py
  custom_components/volkswagencarnet/const.py
  custom_components/volkswagencarnet/manifest.json
  custom_components/volkswagencarnet/strings.json
  custom_components/volkswagencarnet/translations/en.json
  requirements.txt
Labels: bug

#303 Update README.md
  README.md
Labels: enhancement

#314 Update to info working regions and home assistant branding
  README.md
Labels: enhancement

#313 Added iot_class
  custom_components/volkswagencarnet/manifest.json
Labels: enhancement

#312 Add Polish translations
  custom_components/volkswagencarnet/translations/pl.json
Labels: enhancement
