Repository robinostlund/homeassistant-volkswagencarnet, pull requests merged in 2021-04, with the labels that each got.

#274 adding validate issue.yaml
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/workflows/validate_issue.yaml
Labels: enhancement

#275 removing auto close issues
  .github/pull_request_template.md
  .github/workflows/validate_issue.yaml
Labels: enhancement

#277 Uses the new api module and added some error handling
  custom_components/volkswagencarnet/__init__.py
  custom_components/volkswagencarnet/binary_sensor.py
  custom_components/volkswagencarnet/config_flow.py
  custom_components/volkswagencarnet/const.py
  custom_components/volkswagencarnet/manifest.json
  custom_components/volkswagencarnet/sensor.py
  custom_components/volkswagencarnet/strings.json
  custom_components/volkswagencarnet/switch.py
  custom_components/volkswagencarnet/translations/en.json
  requirements.txt
Labels: bug, enhancement

#278 Revert the package renaming
  custom_components/volkswagencarnet/__init__.py
  custom_components/volkswagencarnet/config_flow.py
  custom_components/volkswagencarnet/manifest.json
  requirements.txt
Labels: bug

#279 Bumps api module version
  custom_components/volkswagencarnet/manifest.json
  requirements.txt
Labels: enhancement
