Repository robinostlund/homeassistant-volkswagencarnet, pull requests merged in 2022-02, with the labels that each got.

#365 making update_manifest.py set requirements from requirements.txt
  .github/dependabot.yml
  .github/workflows/cron.yaml
  .github/workflows/release.yaml
  .github/workflows/validate.yaml
  custom_components/volkswagencarnet/manifest.json
  manage/update_manifest.py
  requirements.txt
Labels: enhancement

#373 changing license
  LICENSE.md
Labels: enhancement

#366 Update imports to work with volkswagencarnet package fixes
  custom_components/volkswagencarnet/__init__.py
  custom_components/volkswagencarnet/config_flow.py
Labels: dependencies

#369 Implement overridden functions, add type hinting
  custom_components/volkswagencarnet/__init__.py
  custom_components/volkswagencarnet/climate.py
  custom_components/volkswagencarnet/device_tracker.py
  custom_components/volkswagencarnet/lock.py
  custom_components/volkswagencarnet/switch.py
Labels: enhancement

#376 add black lint check
  .github/workflows/validate.yaml
  custom_components/volkswagencarnet/__init__.py
  custom_components/volkswagencarnet/binary_sensor.py
  custom_components/volkswagencarnet/climate.py
  custom_components/volkswagencarnet/config_flow.py
  custom_components/volkswagencarnet/const.py
  custom_components/volkswagencarnet/device_tracker.py
  custom_components/volkswagencarnet/lock.py
  custom_components/volkswagencarnet/sensor.py
  custom_components/volkswagencarnet/switch.py
  manage/update_manifest.py
Labels: enhancement

#379 Removal of login regions.
  README.md
Labels: enhancement

#385 adding snyk
  .github/workflows/snyk.yaml
Labels: enhancement

#392 Update translations for norwegian nynorsk
  custom_components/volkswagencarnet/translations/nn.json
Labels: enhancement, translation

#394 Add note about dependencies in source installation
  README.md
Labels: enhancement
