Repository robinostlund/homeassistant-volkswagencarnet, pull requests merged in 2022-03, with the labels that each got.

#400 Add Brazilian Portuguese Translation
  custom_components/volkswagencarnet/translations/pt-BR.json
Labels: enhancement, translation

#404 Add "translation" as valid PR label
  .github/workflows/validate_pr.yaml
Labels: bug

#403 Allow reconfiguration
  custom_components/volkswagencarnet/__init__.py
  custom_components/volkswagencarnet/binary_sensor.py
  custom_components/volkswagencarnet/config_flow.py
  custom_components/volkswagencarnet/const.py
  custom_components/volkswagencarnet/device_tracker.py
  custom_components/volkswagencarnet/services.py
  custom_components/volkswagencarnet/strings.json
  custom_components/volkswagencarnet/switch.py
  custom_components/volkswagencarnet/translations/en.json
  custom_components/volkswagencarnet/translations/fi.json
  custom_components/volkswagencarnet/translations/nb.json
  custom_components/volkswagencarnet/translations/nn.json
  custom_components/volkswagencarnet/translations/pl.json
  custom_components/volkswagencarnet/translations/pt-BR.json
  custom_components/volkswagencarnet/util.py
  requirements.test.txt
  tests/config_flow_test.py
  tests/conftest.py
  tests/timer_services_test.py
  tests/util_test.py
Labels: enhancement

#409 Statistics
  .pre-commit-config.yaml
  custom_components/volkswagencarnet/__init__.py
  custom_components/volkswagencarnet/binary_sensor.py
  custom_components/volkswagencarnet/climate.py
  custom_components/volkswagencarnet/config_flow.py
  custom_components/volkswagencarnet/device_tracker.py
  custom_components/volkswagencarnet/lock.py
  custom_components/volkswagencarnet/sensor.py
  custom_components/volkswagencarnet/services.py
  custom_components/volkswagencarnet/switch.py
  requirements.txt
Labels: enhancement
