Repository robinostlund/homeassistant-volkswagencarnet, pull requests merged in 2022-01, with the labels that each got.

#351 [BUG]: Fix en, update nb
  custom_components/volkswagencarnet/translations/en.json
  custom_components/volkswagencarnet/translations/nb.json
Labels: enhancement

#355 bumping volkswagencarnet version
  .github/dependabot.yml
  custom_components/volkswagencarnet/manifest.json
  hacs.json
  requirements.txt
Labels: enhancement

#356 bumping volkswagencarnet version
  custom_components/volkswagencarnet/manifest.json
  requirements.txt
Labels: bug

#357 Dependabot updates
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/validate_pr.yaml
Labels: dependencies

#358 adding codequality to workflow
  .github/workflows/codeql-analysis.yml
Labels: enhancement
