Repository robinostlund/homeassistant-volkswagencarnet, pull requests merged in 2024-02, with the labels that each got.

#563 New beta release
  requirements.txt
Labels: enhancement

#574 New climatisation controls with temperature
  custom_components/volkswagencarnet/__init__.py
  custom_components/volkswagencarnet/binary_sensor.py
  custom_components/volkswagencarnet/climate.py
  custom_components/volkswagencarnet/const.py
  custom_components/volkswagencarnet/device_tracker.py
  custom_components/volkswagencarnet/lock.py
  custom_components/volkswagencarnet/sensor.py
  custom_components/volkswagencarnet/services.py
  custom_components/volkswagencarnet/switch.py
  manage/update_manifest.py
  tests/conftest.py
  tests/hass_mocks.py
  tests/timer_services_test.py
  tests/util_test.py
Labels: enhancement

#575 New release
  requirements.txt
Labels: enhancement

#576 Update minimum Home Assistant version
  hacs.json
Labels: dependencies

#578 New release
  requirements.txt
Labels: bug

#579 v4.5.5
  custom_components/volkswagencarnet/__init__.py
  custom_components/volkswagencarnet/const.py
  custom_components/volkswagencarnet/number.py
  custom_components/volkswagencarnet/services.py
  custom_components/volkswagencarnet/switch.py
Labels: enhancement
